INSERT INTO public.deals (project_name, hq_location, sector, funding_round, funding_amount, valuation_terms, source, bu_category, description, benchmark_companies, followers, status, feedback_notes, financials, deal_date, leads, folder_link, key_contacts, pre_investors) VALUES
('Anthropic', 'San Francisco, USA', 'AI/LLM', 'Series D', '$2B', '$60B valuation', 'Direct', 'Growth', 'Leading AI safety company developing Claude, a next-generation AI assistant focused on being helpful, harmless, and honest.', 'OpenAI, Google DeepMind', 'Spark Capital, Salesforce Ventures', 'Invested', 'Strong technical team, clear differentiation on safety. Long-term moat potential.', 'ARR >$500M, growing 300% YoY', '2025-01-15', 'Internal Research', 'https://notion.so/anthropic-deal', 'Dario Amodei (CEO)', 'Google, Spark Capital'),
('Perplexity AI', 'San Francisco, USA', 'AI/Search', 'Series B', '$500M', '$9B valuation', 'Referral', 'Venture', 'AI-powered answer engine that provides direct answers with citations, disrupting traditional search.', 'Google, Bing, You.com', 'IVP, NEA', 'Follow', 'Impressive growth, but search market is highly competitive.', 'MAU 100M+, Revenue $100M ARR', '2025-02-20', 'Partner Network', 'https://drive.google.com/perplexity', 'Aravind Srinivas (CEO)', 'Nvidia, Jeff Bezos'),
('Figure AI', 'Sunnyvale, USA', 'Robotics/AI', 'Series B', '$675M', '$2.6B valuation', 'Conference', 'Venture', 'Developing general-purpose humanoid robots for manufacturing and logistics applications.', 'Boston Dynamics, Tesla Bot', 'Microsoft, OpenAI', 'Due Diligence', 'Revolutionary technology, but hardware scaling is challenging.', 'Pre-revenue, significant R&D burn', '2025-03-10', 'Tech Summit 2025', 'https://notion.so/figure-ai', 'Brett Adcock (CEO)', 'Bezos Expeditions, Parkway Venture'),
('Groq', 'Mountain View, USA', 'AI Infrastructure', 'Series D', '$640M', '$2.8B valuation', 'Direct', 'Growth', 'AI chip company with LPU (Language Processing Unit) technology enabling fastest inference speeds.', 'Nvidia, Cerebras, AMD', 'Tiger Global, D1 Capital', 'Follow', 'Impressive demo speeds, need to validate enterprise adoption.', 'Growing cloud revenue, hardware sales ramping', '2025-01-28', 'Technical Due Diligence', 'https://drive.google.com/groq', 'Jonathan Ross (CEO)', 'Tiger Global, Addition'),
('Mistral AI', 'Paris, France', 'AI/LLM', 'Series B', '$640M', '$6B valuation', 'Network', 'Venture', 'European AI lab building open-weight and commercial LLMs, positioned as OpenAI alternative.', 'OpenAI, Anthropic, Cohere', 'a16z, Lightspeed', 'Invested', 'Strong European presence, open-source strategy is differentiating.', 'Enterprise contracts growing rapidly', '2025-02-05', 'European VC Network', 'https://notion.so/mistral', 'Arthur Mensch (CEO)', 'a16z, General Catalyst'),
('Scale AI', 'San Francisco, USA', 'AI/Data', 'Series F', '$1B', '$13.8B valuation', 'Referral', 'Growth', 'AI data infrastructure company providing data labeling and synthetic data generation for ML models.', 'Labelbox, Snorkel AI', 'Accel, Tiger Global', 'Pass', 'Market leader but commoditization risk in labeling space.', 'Revenue $750M+, profitable', '2025-03-01', 'Portfolio Company', 'https://drive.google.com/scale', 'Alexandr Wang (CEO)', 'Founders Fund, Index Ventures'),
('xAI', 'Austin, USA', 'AI/LLM', 'Series B', '$6B', '$24B valuation', 'Direct', 'Growth', 'Elon Musks AI company building Grok, integrated with X platform for real-time information access.', 'OpenAI, Anthropic', 'a16z, Sequoia', 'Follow', 'Strong distribution through X, but governance concerns.', 'Integrated with X premium subscriptions', '2025-02-15', 'Industry Contact', 'https://notion.so/xai-deal', 'Elon Musk (Owner)', 'Valor Equity, Sequoia'),
('Runway', 'New York, USA', 'AI/Creative', 'Series D', '$300M', '$4B valuation', 'Conference', 'Venture', 'AI-powered video generation and editing platform, pioneering generative video technology.', 'Pika, Stability AI, Adobe', 'Nvidia, Google', 'Due Diligence', 'Leading in video generation, Hollywood partnerships promising.', 'ARR $100M+, enterprise growth strong', '2025-03-20', 'Creative Tech Summit', 'https://drive.google.com/runway', 'Cristóbal Valenzuela (CEO)', 'Lux Capital, Coatue'),
('Databricks', 'San Francisco, USA', 'Data/AI', 'Series J', '$10B', '$62B valuation', 'Direct', 'Growth', 'Unified analytics and AI platform combining data warehousing, engineering, and machine learning.', 'Snowflake, Palantir', 'a16z, Thrive Capital', 'Invested', 'Clear market leader in data lakehouse, strong enterprise moat.', 'Revenue $2.4B+, approaching profitability', '2025-01-10', 'Internal Research', 'https://notion.so/databricks', 'Ali Ghodsi (CEO)', 'a16z, T. Rowe Price'),
('Cohere', 'Toronto, Canada', 'AI/Enterprise', 'Series D', '$500M', '$5.5B valuation', 'Network', 'Venture', 'Enterprise-focused LLM company offering customizable AI models for business applications.', 'OpenAI, Anthropic, Google', 'Nvidia, Salesforce', 'Follow', 'Strong enterprise positioning, but competitive pressure from big tech.', 'Enterprise ARR growing 200%+', '2025-02-28', 'Canadian VC Network', 'https://drive.google.com/cohere', 'Aidan Gomez (CEO)', 'Index Ventures, Radical Ventures');